// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KakaIMClientPresident.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class KIMProtoNodeInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum KIMProtoResponseNodeMessage_Error

typedef GPB_ENUM(KIMProtoResponseNodeMessage_Error) {
  /** 服务器内部错误 */
  KIMProtoResponseNodeMessage_Error_ServerInternalError = 1,
};

GPBEnumDescriptor *KIMProtoResponseNodeMessage_Error_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL KIMProtoResponseNodeMessage_Error_IsValidValue(int32_t value);

#pragma mark - KIMProtoKakaImclientPresidentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface KIMProtoKakaImclientPresidentRoot : GPBRootObject
@end

#pragma mark - KIMProtoRequestNodeMessage

typedef GPB_ENUM(KIMProtoRequestNodeMessage_FieldNumber) {
  KIMProtoRequestNodeMessage_FieldNumber_UserAccount = 1,
  KIMProtoRequestNodeMessage_FieldNumber_Longitude = 2,
  KIMProtoRequestNodeMessage_FieldNumber_Latitude = 3,
};

/**
 * 请求登陆Node
 **/
@interface KIMProtoRequestNodeMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAccount;
/** Test to see if @c userAccount has been set. */
@property(nonatomic, readwrite) BOOL hasUserAccount;

/** 经度 */
@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite) BOOL hasLongitude;
/** 纬度 */
@property(nonatomic, readwrite) float latitude;

@property(nonatomic, readwrite) BOOL hasLatitude;
@end

#pragma mark - KIMProtoNodeInfo

typedef GPB_ENUM(KIMProtoNodeInfo_FieldNumber) {
  KIMProtoNodeInfo_FieldNumber_IpAddr = 1,
  KIMProtoNodeInfo_FieldNumber_Port = 2,
};

@interface KIMProtoNodeInfo : GPBMessage

/** IP地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ipAddr;
/** Test to see if @c ipAddr has been set. */
@property(nonatomic, readwrite) BOOL hasIpAddr;

/** 端口号 */
@property(nonatomic, readwrite) int32_t port;

@property(nonatomic, readwrite) BOOL hasPort;
@end

#pragma mark - KIMProtoResponseNodeMessage

typedef GPB_ENUM(KIMProtoResponseNodeMessage_FieldNumber) {
  KIMProtoResponseNodeMessage_FieldNumber_NodeArray = 1,
  KIMProtoResponseNodeMessage_FieldNumber_ErrorType = 2,
};

/**
 * 响应登陆Node
 **/
@interface KIMProtoResponseNodeMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KIMProtoNodeInfo*> *nodeArray;
/** The number of items in @c nodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodeArray_Count;

@property(nonatomic, readwrite) KIMProtoResponseNodeMessage_Error errorType;

@property(nonatomic, readwrite) BOOL hasErrorType;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
